theme: jekyll-theme-cayman
title: Welcome to Alex Sandoval's homepage!
description: Feel free to bookmark this to keep an eye on my project updates.


<body>
  <div class="wrapper">
    {% include sidebar.html %}

    <div class="main-wrapper">
        {{ content }}
    </div>
  </div>

  {% include footer.html %}

{% include scripts.html %}
</body>

</html>
